[package]
name = "array_type"
version = "0.1.0"
authors = ["João Santos <jocatoca3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
